#!/bin/sh

set -e

# Определяем имя файла для сайта, используя второй аргумент командной строки или значение по умолчанию
SITE_FILE_NAME="${2:-sunpp-20.09.03}.tgz"
IMAGE_DOMAIN="registry.sunpp.cns.atom"
WEAVE_FILE_NAME="weave-2.5.1.tar.gz"
CERT_FILE_NAME="certificates.tgz"
BASE_URL="http://sdn.dc.cns.atom/install/"
INSTALL_DIR="/opt/ekatra/"
SCRIPT_VERSION="0.3.0"

# Функция вывода информации о использовании скрипта
# cat >&2 <<EOF:    Это начало конструкции, которая направляет вывод текста в стандартный поток ошибок (>&2).
#                   Здесь <<EOF указывает на начало многострочного текста, который будет передан в команду cat для вывода
# Usage::           Это заголовок, который указывает пользователю, что выводится информация о способах использования скрипта.
# $0:               Эта переменная представляет имя текущего скрипта
# --help | help:    Это описание первой строки справки, которая объясняет, как получить помощь по использованию скрипта.
#                   Когда пользователь вызывает скрипт с --help или help, он ожидает увидеть эту информацию.
# --version | version:   Следующая строка справки объясняет, как получить текущую версию скрипта.
#                        Пользователь может запросить версию скрипта, вызвав --version или version.
# setup             может инициировать установку необходимых зависимостей или настроек.
# upgrade           может выполнять обновление программного обеспечения или конфигураций.
# download          может загружать необходимые файлы или данные.
# changelog         может выводить изменения и исправления в последней версии программы или скрипта.
# EOF:              Это ключевое слово, которое завершает блок многострочного текста, который будет передан в cat для вывода.
#                   Он указывает на конец текста справки.
usage() {
    cat >&2 <<EOF
Usage:
$0 --help | help
      --version | version
      setup
      upgrade
      download
      changelog
EOF
}

# Функция сохранения образов Docker
# docker images:                        выводит список всех Docker образов в системе.
# grep "$IMAGE_DOMAIN":                 Фильтрует вывод, оставляя строки содержащие указанный домен (например, registry.sunpp.cns.atom).
# awk '{printf "%s:%s ", $1, $2}':      для форматирования вывода docker images. Он берёт первый ($1) и второй ($2) столбцы каждой строки вывода #                                       (обычно это репозиторий и тег образа) и выводит их в формате репозиторий:тег .
# xargs --no-run-if-empty docker save:  Xargs - для передачи форматированного списка образов команде docker save.
#                                       Флаг --no-run-if-empty предотвращает выполнение команды, если список пуст.
#                                       docker save сохраняет указанные образы в архив.
# gzip -c > images.gz:                  gzip упаковывает данные, которые были сохранены docker save, и записывает результат в файл images.gz.
save_images() {
    docker images | grep "$IMAGE_DOMAIN" | awk '{printf "%s:%s ", $1, $2}' | xargs --no-run-if-empty docker save | gzip -c > images.gz
}

# Функция пуша образов Docker в реестр
# Тут следует дать пояснение:
# while read -r line; do docker push $line ;done;:  
#     Этот блок выполняет цикл по каждой строке вывода, прочитанной из предыдущего шага.
#     Каждая строка, содержащая пару репозиторий:тег, передаётся в команду docker push $line,
#     где $line представляет собой текущую строку с репозиторием и тегом образа.
#     Команда docker push загружает (пушит) образ на указанный реестр Docker.
push_images() {
    docker images | grep "$IMAGE_DOMAIN" | awk '{printf "%s:%s\n", $1, $2}' | while read -r line; do docker push $line ;done;
}

# Функция сбора информации о системе
gather_facts() {

    # Проверяем наличие необходимых команд в системе и если нет - выход
    if [ ! -x /usr/bin/curl ] ; then
        command -v curl >/dev/null 2>&1 || { echo >&2 "Please install curl"; exit 1; }
    fi

    if [ ! -x /usr/bin/python ] ; then
         echo >&2 "Please install python"; exit 1;
    fi

    # Определяем операционную систему хоста
    # Если команда lsb_release доступна в системе
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$NAME
        VER=$VERSION_ID
    # иначе если /etc/lsb-release существует, то содержимое загружается 
    elif type lsb_release >/dev/null 2>&1; then
        OS=$(lsb_release -si)
        VER=$(lsb_release -sr)
    elif [ -f /etc/lsb-release ]; then
        . /etc/lsb-release
        OS=$DISTRIB_ID
        VER=$DISTRIB_RELEASE
    # иначе если файл /etc/debian_version существует
    elif [ -f /etc/debian_version ]; then
        OS=Debian
        VER=$(cat /etc/debian_version)
    # или просто вот так
    else
        OS=$(uname -s)
        VER=$(uname -r)
    fi
    # Вывод OS и Version
    echo "Detected OS $OS $VER"
    curl -V
    python -V
}

# Функция загрузки Docker в зависимости от ОС
download_docker() {
    case $OS in
    Debian*)
        DOCKER_FILE_NAME=docker-debian-stretch.tgz
        ;;
    Ubuntu)
        DOCKER_FILE_NAME=docker-ubuntu-bionic.tgz
        ;;
    CentOS*)
        DOCKER_FILE_NAME=docker-centos-7.tgz
        ;;
    *)
        echo "Unsupported host OS: $OS"
        exit 1
        ;;
    esac

    if [ ! -f "$DOCKER_FILE_NAME" ] ; then
        echo "Download docker $BASE_URL/terraform/$DOCKER_FILE_NAME"
        curl --fail -k "$BASE_URL/terraform/$DOCKER_FILE_NAME" -o "$DOCKER_FILE_NAME"
    else
        echo "File $DOCKER_FILE_NAME present"
    fi
}

# Функция загрузки Weave
download_weave() {
    # Если файл не существует, то подгрузим с помощью curl
    if [ ! -f "$WEAVE_FILE_NAME" ] ; then
        echo "Download weave $BASE_URL/terraform/$WEAVE_FILE_NAME"
        curl --fail -k "$BASE_URL/terraform/$WEAVE_FILE_NAME" -o "$WEAVE_FILE_NAME"
    # иначе сообщим о наличие
    else
        echo "File $WEAVE_FILE_NAME present"
    fi
}

# Функция загрузки сайта
download_site() {
    if [ ! -f "$SITE_FILE_NAME" ] ; then
        echo "Download domain $BASE_URL/sites/$SITE_FILE_NAME"
        curl --fail -k "$BASE_URL/sites/$SITE_FILE_NAME" -o "$SITE_FILE_NAME"
    else
        echo "File $SITE_FILE_NAME present"
    fi
}

# Функция установки Docker
install_docker() {

    echo "Install docker"
    TEMP_DIR=/tmp/ekatra/docker
    mkdir -p "$TEMP_DIR"
    # ранее был загружен файл DOCKER_FILE_NAME см. download_docker()
    tar -x --directory="$TEMP_DIR" -zf "$DOCKER_FILE_NAME"


    # Установка сертификатов, если они присутствуют
    if ls $TEMP_DIR/*.crt 1> /dev/null 2>&1;  then
        echo "Install certificat"
        case $OS in
        Debian*|Ubuntu)
            sudo cp $TEMP_DIR/*.crt /usr/local/share/ca-certificates/
            sudo update-ca-certificates
            ;;
        CentOS*)
            sudo update-ca-trust enable
            sudo cp $TEMP_DIR/*.crt /etc/pki/ca-trust/source/anchors/
            sudo update-ca-trust extract
            ;;
        *)
            echo "Unsupported host OS: $OS"
            exit 1
            ;;
        esac
    fi

    # Включаем live restore для Docker
    sudo mkdir -p "/etc/docker"
    bash -c 'echo -e "{\n\"live-restore\": true\n}" | sudo tee /etc/docker/daemon.json > /dev/null'

    # Устанавливаем Docker в зависимости от ОС
    case $OS in
    Debian*|Ubuntu)
        sudo dpkg -i $TEMP_DIR/*.deb
        ;;
    CentOS*)
        sudo yum localinstall -y --nogpgcheck $TEMP_DIR/*.rpm
        ;;
    *)
        echo "Unsupported host OS: $OS"
        exit 1
        ;;
    esac

    # Устанавливаем docker-volume-local-persist, если он присутствует
    if [ -f "$TEMP_DIR/docker-volume-local-persist" ] &&
       [ ! -f "/usr/bin/docker-volume-local-persist" ] ; then
        sudo cp "$TEMP_DIR/docker-volume-local-persist" "/usr/bin/"
        sudo cp "$TEMP_DIR/docker-volume-local-persist.service" "/etc/systemd/system/"
        sudo chmod +x /usr/bin/docker-volume-local-persist
        sudo systemctl daemon-reload
        sudo systemctl enable docker-volume-local-persist
        sudo systemctl start docker-volume-local-persist
    fi

    rm -r "$TEMP_DIR"
}

# Функция установки Weave
install_weave() {
    echo "Install weave"
    sudo docker load -i $WEAVE_FILE_NAME
    sudo tar -x --directory=/usr/local/bin -zf "$WEAVE_FILE_NAME" weave
    sudo chmod +x /usr/local/bin/weave
}

# Функция установки сертификатов
install_crt() {
    CERT_DIR="$INSTALL_DIR/.certs"
    if [ -f "$CERT_FILE_NAME" ] ; then
        echo "File $CERT_FILE_NAME present"
        echo "Install Domain certificates from $CERT_FILE_NAME"
        sudo mkdir -p "$CERT_DIR"
        sudo tar -x --directory="$CERT_DIR" -zf "$CERT_FILE_NAME"

        # Переименовываем файлы .cer в .crt, если они есть
        sudo find "$CERT_DIR" -depth -name "*.cer" -exec sh -c 'mv "$1" "${1%.cer}.crt"' _ {} \;

        # Устанавливаем сертификаты в зависимости от ОС
        if ls $CERT_DIR/*CA*.crt 1> /dev/null 2>&1;  then
            case $OS in
            Debian*|Ubuntu)
                sudo cp $CERT_DIR/*CA*.crt /usr/local/share/ca-certificates/
                sudo update-ca-certificates
                ;;
            CentOS*)
                sudo update-ca-trust enable
                sudo cp $CERT_DIR/*CA*.crt /etc/pki/ca-trust/source/anchors/
                sudo update-ca-trust extract
                ;;
            *)
                echo "Unsupported host OS: $OS"
                exit 1
                ;;
            esac
        fi
    else
        echo "Domain certificates $CERT_FILE_NAME not present."
    fi
}

# Функция установки сайта
install_site() {

    # Проверяем, что каталог установки пустой
    if [ -d "$INSTALL_DIR" ] && [ "$(ls -A $INSTALL_DIR | grep -v .certs)" ]; then
        echo "Installation aborted. $INSTALL_DIR is not Empty"
        exit 1
    fi

    # Устанавливаем сайт,



    # Устанавливаем сайт, если архив существует
    if [ -f "$SITE_FILE_NAME" ] ; then
        sudo mkdir -p "$INSTALL_DIR"
        sudo tar -x --directory="$INSTALL_DIR" -zf "$SITE_FILE_NAME"
    else
        echo "File not found $SITE_FILE_NAME"
        exit 1
    fi

    # Запускаем скрипт настройки, если он существует
    if [ -f "$INSTALL_DIR/.install/setup.sh" ] ; then
        cd "$INSTALL_DIR/.install/"
        sudo "./setup.sh"
    fi
}

# Функция обновления сайта
upgrade_site() {
    TEMP_INSTALL_DIR=/tmp/ekatra/upgrade

    # Распаковываем архив с обновлением, если он существует
    if [ -f "$SITE_FILE_NAME" ] ; then
        sudo mkdir -p "$TEMP_INSTALL_DIR"
        sudo tar -x --directory="$TEMP_INSTALL_DIR" -zf "$SITE_FILE_NAME"
    else
        echo "File not found $SITE_FILE_NAME"
        exit 1
    fi

    # Запускаем скрипт обновления, если он существует
    if [ -f "$TEMP_INSTALL_DIR/.install/upgrade.sh" ] ; then
        cd "$TEMP_INSTALL_DIR/.install/"
        sudo "./upgrade.sh"
    fi
}

# Функция вывода изменений
changelog() {
    if [ -f "$SITE_FILE_NAME" ] ; then
        tar -xOzf $SITE_FILE_NAME --to-stdout --wildcards './**/CHANGELOG*.md' | more
    fi
}

######################################################################
# Основное тело скрипта
######################################################################

# Обработка спец команд $1, которые выполняются локально на клиенте
case "$1" in
    help|--help)
        usage
        exit 0
        ;;
    version|--version)
        echo "$SCRIPT_VERSION"
        exit 0
        ;;
    changelog)
        download_site
        changelog
        exit 0
        ;;
    setup)
        gather_facts
        download_docker
        download_weave
        download_site
        install_docker
        install_weave
        install_crt
        install_site
        ;;
    upgrade)
        gather_facts
        download_site
        install_crt
        upgrade_site
        ;;
    download)
        gather_facts
        download_docker
        download_weave
        download_site
        ;;
    *)
        usage
        exit 1
        ;;
esac
